import type { LangCode } from './translations';

export interface LocalizedPet {
  name: string;
  tagline: string;
  phrases: string[];
}

export type PetLocale = Record<string, LocalizedPet>;

const en: PetLocale = {
  octopus: { name: 'Otto the Octopus', tagline: 'Your eco mascot — free starter pet.', phrases: ['Eight arms, eight upcycle projects at once!', 'I squeezed through a jar lid just to recycle it!', 'Did you know I have three hearts? All green!', 'Blue blood, green lifestyle — that is me.', 'I can open jars, bottles, and minds to recycling.'] },
  turtle: { name: 'Tina the Turtle', tagline: 'Slow and steady wins the eco race.', phrases: ['I have lived 100 years — I have seen the plastic tide rise.', 'My shell is my home; the ocean is yours, keep it clean.', 'I munch on jellyfish, not plastic bags. Please tell them apart!', 'Slow steps still cross the ocean, friend.', 'I remember when this reef had no litter. Let us bring that back.'] },
  dolphin: { name: 'Dex the Dolphin', tagline: 'Smart and playful in the waves.', phrases: ['I recognize myself in the mirror — and I see trash. Let us fix that!', 'We name each other with whistles. I call you Friend of the Sea.', 'I can flip a bottle cap off with my nose. Upcycle trick!', 'Half my brain sleeps while the other half watches for litter.', 'I pass sponges on my nose as a fashion statement. Reuse, reuse!'] },
  whale: { name: 'Willa the Whale', tagline: 'Gentle giant of the deep.', phrases: ['My song travels 10,000 miles. Today I sing: recycle.', 'I eat plankton, not plastic. Please keep them separate.', 'My heart is the size of a small car — and it beats for the ocean.', 'I breathe once an hour. Every breath is precious, like every scrap.', 'The deep blue is my cathedral. Keep it pristine.'] },
  albatross: { name: 'Alby the Albatross', tagline: 'Soars above the plastic tide.', phrases: ['I fly 600 miles in a day and see every plastic bottle below.', 'I lock my wings and glide for hours — zero fuel, zero waste. Be like me!', 'I scoop squid from the surface. Not bottle caps. Please.', 'My wings span 11 feet. Big enough to carry big ideas.', 'I nest on remote islands. Even they are not safe from plastic.'] },
  seal: { name: 'Sage the Seal', tagline: 'Sleek guardian of the shore.', phrases: ['I can dive 1,000 feet deep. I bring back stories, not trash.', 'My whiskers feel fish in the dark. They also feel microplastics. Yuck.', 'I sunbathe on rocks — and on bottle caps. Less of those, please.', 'I hold my breath for two hours. Long enough to clean a whole beach.', 'I bark at my pups. Today I bark at litterbugs!'] },
  crab: { name: 'Coco the Crab', tagline: 'Snappy little recycler.', phrases: ['I walk sideways — toward sustainability, obviously.', 'My claws can snip a plastic ring in half. Save a turtle, snip yours too!', 'I dig burrows in the sand. I keep finding straws in them. Stop that!', 'I molt my shell once a year. You cannot molt, so reuse instead.', 'Tide pools are my living room. Wipe your feet — and your waste.'] },
  otter: { name: 'Ollie the Otter', tagline: 'Playful river cleaner.', phrases: ['I use a rock as my favorite tool. Same rock, 20 years. Reuse champion!', 'I have a pocket under my arm for my rock. Where is your pocket for reuse?', 'I float on my back and crack open clams. I also crack open upcycle ideas.', 'I hold hands with my friends while sleeping so we do not drift. Hold the planet too.', 'My fur is the densest in the animal kingdom. Keep oil out of it, please.'] },
  fish: { name: 'Finn the Fish', tagline: 'Tiny but mighty for the ocean.', phrases: ['I school with 10,000 friends. Together we are a tide of change.', 'I breathe through my gills. Plastic clogs them. Keep water clean.', 'I am small, but I eat algae that would smother the reef. Small job, big deal.', 'My scales reflect light like a rainbow. Plastic does not. Pick it up!', 'I was born knowing where to go. Let us make sure the reef is still there.'] },
};

const pt: PetLocale = {
  octopus: { name: 'Otto, o Polvo', tagline: 'Se mascote eco — pet inicial grátis.', phrases: ['Oito braços, oito projetos de reciclagem ao mesmo tempo!', 'Apertei uma tampa de vidro só para reciclá-la!', 'Sabia que tenho três corações? Todos verdes!', 'Sangue azul, estilo de vida verde — esse sou eu.', 'Abro potes, garrafas e mentes para a reciclagem.'] },
  turtle: { name: 'Tina, a Tartaruga', tagline: 'Devagar e sempre ganha a corrida eco.', phrases: ['Vivi 100 anos — vi a maré de plástico subir.', 'Minha carapaça é minha casa; o oceano é seu, mantenha-o limpo.', 'Como águas-vivas, não sacolas plásticas. Por favor, saiba diferenciar!', 'Passos lentos ainda cruzam o oceano, amigo.', 'Lembro de quando este recife não tinha lixo. Vamos trazer isso de volta.'] },
  dolphin: { name: 'Dex, o Golfinho', tagline: 'Esperto e brincalhão nas ondas.', phrases: ['Me reconheço no espelho — e vejo lixo. Vamos consertar isso!', 'Nos nomeamos com assobios. Eu te chamo de Amigo do Mar.', 'Consigo arremessar uma tampa com o focinho. Truque de reciclagem!', 'Metade do meu cérebro dorme enquanto a outra vigia o lixo.', 'Uso esponjas no focinho como moda. Reutilizar, reutilizar!'] },
  whale: { name: 'Willa, a Baleia', tagline: 'Gigante gentil das profundezas.', phrases: ['Meu canto viaja 16.000 km. Hoje eu canto: recicle.', 'Como plâncton, não plástico. Por favor, mantenha-os separados.', 'Meu coração é do tamanho de um carro pequeno — e bate pelo oceano.', 'Respiro uma vez por hora. Cada respiração é preciosa, como cada sobra.', 'O azul profundo é minha catedral. Mantenha-o imaculado.'] },
  albatross: { name: 'Alby, o Albatroz', tagline: 'Planador acima da maré de plástico.', phrases: ['Voo 1.000 km por dia e vejo cada garrafa plástica lá embaixo.', 'Travo as asas e plano por horas — zero combustível, zero lixo. Seja como eu!', 'Pego lulas na superfície. Não tampas de garrafa. Por favor.', 'Minhas asas têm 3,5 metros. Grandes o suficiente para carregar grandes ideias.', 'Ninho em ilhas remotas. Mesmo elas não estão salvas do plástico.'] },
  seal: { name: 'Sage, a Foca', tagline: 'Guardiã elegante da costa.', phrases: ['Mergulho a 300 metros de profundidade. Trago histórias, não lixo.', 'Meus bigodes sentem peixes no escuro. Também sentem microplásticos. Eca.', 'Tomo sol nas rochas — e em tampas de garrafa. Menos disso, por favor.', 'Seguro a respiração por duas horas. Suficiente para limpar uma praia inteira.', 'Latro para meus filhotes. Hoje eu latro para sujões!'] },
  crab: { name: 'Coco, o Caranguejo', tagline: 'Pequeno reciclador estaladiço.', phrases: ['Ando de lado — em direção à sustentabilidade, obviamente.', 'Minhas garras cortam um anel de plástico ao meio. Salve uma tartaruga, corte os seus também!', 'Cavo tocas na areia. Fico achando canudos nelas. Pare com isso!', 'Troco minha casca uma vez por ano. Você não pode trocar, então reutilize.', 'Poças de maré são minha sala. Limpe os pés — e seu lixo.'] },
  otter: { name: 'Ollie, a Lontra', tagline: 'Brincalhão limpador de rios.', phrases: ['Uso uma pedra como minha ferramenta favorita. Mesma pedra, 20 anos. Campeão da reutilização!', 'Tenho um bolso debaixo do braço para minha pedra. Onde está o seu bolso para reutilização?', 'Fluto de costas e quebro conchas. Também quebro ideias de reciclagem.', 'Deito mãos com meus amigos enquanto durmo para não nos afastarmos. Segure o planeta também.', 'Minha pele é a mais densa do reino animal. Mantenha óleo longe dela, por favor.'] },
  fish: { name: 'Finn, o Peixe', tagline: 'Pequeno, mas poderoso pelo oceano.', phrases: ['Ando em cardume com 10.000 amigos. Juntos somos uma maré de mudança.', 'Respiro pelas guelras. Plástico as entope. Mantenha a água limpa.', 'Sou pequeno, mas como algas que sufocariam o recife. Trabalho pequeno, grande impacto.', 'Minhas escamas refletem luz como um arco-íris. Plástico não. Pegue-o!', 'Nasci sabendo para onde ir. Vamos garantir que o recife ainda esteja lá.'] },
};

const es: PetLocale = {
  octopus: { name: 'Otto el Pulpo', tagline: 'Tu mascota eco — mascota inicial gratis.', phrases: ['¡Ocho brazos, ocho proyectos de reciclaje a la vez!', '¡Apreté por una tapa de frasco solo para reciclarla!', '¿Sabías que tengo tres corazones? ¡Todos verdes!', 'Sangre azul, estilo de vida verde — ese soy yo.', 'Abro frascos, botellas y mentes al reciclaje.'] },
  turtle: { name: 'Tina la Tortuga', tagline: 'Lento y constante gana la carrera eco.', phrases: ['He vivido 100 años — he visto subir la marea de plástico.', 'Mi caparazón es mi hogar; el océano es tuyo, mantenlo limpio.', 'Como medusas, no bolsas de plástico. ¡Por favor, distínguelas!', 'Pasos lentos aún cruzan el océano, amigo.', 'Recuerdo cuando este arrecife no tenía basura. Traigamos eso de vuelta.'] },
  dolphin: { name: 'Dex el Delfín', tagline: 'Listo y juguetón en las olas.', phrases: ['Me reconozco en el espejo — y veo basura. ¡Vamos a arreglarlo!', 'Nos nombramos con silbidos. Yo te llamo Amigo del Mar.', '¡Puedo voltear una tapa con el hocico! ¡Truco de reciclaje!', 'La mitad de mi cerebro duerme mientras la otra vigila la basura.', 'Uso esponjas en el hocico como moda. ¡Reutilizar, reutilizar!'] },
  whale: { name: 'Willa la Ballena', tagline: 'Gigante gentil de las profundidades.', phrases: ['Mi canto viaja 16.000 km. Hoy canto: recicla.', 'Como plancton, no plástico. Por favor, mantenlos separados.', 'Mi corazón es del tamaño de un coche pequeño — y late por el océano.', 'Respiro una vez por hora. Cada respiración es preciosa, como cada sobra.', 'El azul profundo es mi catedral. Mantenla prístina.'] },
  albatross: { name: 'Alby el Albatros', tagline: 'Planea sobre la marea de plástico.', phrases: ['Vuelo 1.000 km al día y veo cada botella de plástico abajo.', 'Trabo mis alas y planeo por horas — cero combustible, cero basura. ¡Sé como yo!', 'Pengo calamares de la superficie. No tapas de botella. Por favor.', 'Mis alas miden 3,5 metros. Suficientes para llevar grandes ideas.', 'Anido en islas remotas. Ni ellas están a salvo del plástico.'] },
  seal: { name: 'Sage la Foca', tagline: 'Guardiana elegante de la orilla.', phrases: ['Puedo bucear 300 metros. Traigo historias, no basura.', 'Mis bigotes sienten peces en la oscuridad. También sienten microplásticos. Puaj.', 'Tomo el sol en rocas — y en tapas de botella. Menos de esas, por favor.', 'Aguanto la respiración dos horas. Suficiente para limpiar una playa entera.', 'Ladro a mis crías. ¡Hoy ladro a los que ensucian!'] },
  crab: { name: 'Coco el Cangrejo', tagline: 'Pequeño reciclador chasquido.', phrases: ['Caminó de lado — hacia la sostenibilidad, obviamente.', 'Mis garras cortan un anillo de plástico por la mitad. ¡Salva una tortuga, corta los tuyos también!', 'Cavo madrigueras en la arena. Sigo encontrando pajitas. ¡Detengan eso!', 'Mudo mi caparazón una vez al año. Tú no puedes mudar, así que reutiliza.', 'Las pozas de marea son mi sala. Limpia tus pies — y tu basura.'] },
  otter: { name: 'Ollie la Nutria', tagline: 'Juguetón limpiador de ríos.', phrases: ['Uso una roca como mi herramienta favorita. Misma roca, 20 años. ¡Campeón de reutilización!', 'Tengo un bolsillo bajo el brazo para mi roca. ¿Dónde está tu bolsillo para reutilizar?', 'Floto de espalda y abro conchas. También abro ideas de reciclaje.', 'Me doy la mano con mis amigos mientras duermo para no derivar. Sujeta el planeta también.', 'Mi pelaje es el más denso del reino animal. Mantén el aceite fuera, por favor.'] },
  fish: { name: 'Finn el Pez', tagline: 'Pequeño pero poderoso por el océano.', phrases: ['Nado en banco con 10.000 amigos. Juntos somos una marea de cambio.', 'Respiro por las agallas. El plástico las obstruye. Mantén el agua limpia.', 'Soy pequeño, pero como algas que sofocarían el arrecife. Trabajo pequeño, gran cosa.', 'Mis escamas reflejan luz como un arcoíris. El plástico no. ¡Recógelo!', 'Nací sabiendo a dónde ir. Asegurémonos de que el arrecife siga ahí.'] },
};

const fr: PetLocale = {
  octopus: { name: 'Otto le Poulpe', tagline: 'Votre mascotte éco — animal de départ gratuit.', phrases: ['Huit bras, huit projets de recyclage à la fois !', 'J\'ai passé une capsule de bocal juste pour la recycler !', 'Le saviez-vous ? J\'ai trois cœurs ! Tous verts !', 'Sang bleu, mode de vie vert — c\'est moi.', 'J\'ouvre des bocaux, des bouteilles et des esprits au recyclage.'] },
  turtle: { name: 'Tina la Tortue', tagline: 'Lent et régulier gagne la course éco.', phrases: ['J\'ai vécu 100 ans — j\'ai vu la marée de plastique monter.', 'Ma carapace est ma maison ; l\'océan est le vôtre, gardez-le propre.', 'Je mange des méduses, pas des sacs plastique. Apprenez à les distinguer !', 'Des pas lents traversent quand même l\'océan, mon ami.', 'Je me souviens quand ce récif n\'avait pas de déchets. Ramenons ça.'] },
  dolphin: { name: 'Dex le Dauphin', tagline: 'Intelligent et joueur dans les vagues.', phrases: ['Je me reconnais dans le miroir — et je vois des déchets. Réparons ça !', 'Nous nous nommons avec des sifflements. Je t\'appelle Ami de la Mer.', 'Je peux faire sauter un bouchon avec mon nez. Tour de recyclage !', 'La moitié de mon cerveau dort pendant que l\'autre surveille les déchets.', 'Je passe des éponges sur mon nez comme mode. Réutiliser, réutiliser !'] },
  whale: { name: 'Willa la Baleine', tagline: 'Géante gentille des profondeurs.', phrases: ['Mon chant parcourt 16 000 km. Aujourd\'hui je chante : recyclez.', 'Je mange du plancton, pas du plastique. Gardez-les séparés.', 'Mon cœur est gros comme une petite voiture — et il bat pour l\'océan.', 'Je respire une fois par heure. Chaque souffle est précieux, comme chaque déchet.', 'Le bleu profond est ma cathédrale. Gardez-la immaculée.'] },
  albatross: { name: 'Alby l\'Albatros', tagline: 'Plane au-dessus de la marée de plastique.', phrases: ['Je vole 1 000 km par jour et je vois chaque bouteille en plastique en bas.', 'Je bloque mes ailes et plane pendant des heures — zéro carburant, zéro déchet. Sois comme moi !', 'Je attrape des calmars à la surface. Pas des bouchons. S\'il te plaît.', 'Mes ailes mesurent 3,5 m. Assez grandes pour porter de grandes idées.', 'Je niche sur des îles reculées. Même elles ne sont pas à l\'abri du plastique.'] },
  seal: { name: 'Sage le Phoque', tagline: 'Gardien élégant du rivage.', phrases: ['Je plonge à 300 m de profondeur. Je ramène des histoires, pas des déchets.', 'Mes moustaches sentent les poissons dans le noir. Elles sentent aussi les microplastiques. Beurk.', 'Je bronze sur les rochers — et sur les bouchons. Moins de ça, s\'il te plaît.', 'Je retiens mon souffle deux heures. Assez pour nettoyer toute une plage.', 'J\'aboie à mes petits. Aujourd\'hui j\'aboie aux pollueurs !'] },
  crab: { name: 'Coco le Crabe', tagline: 'Petit recycleur claquant.', phrases: ['Je marche de côté — vers la durabilité, évidemment.', 'Mes pinces coupent un anneau plastique en deux. Sauve une tortue, coupe les tiens aussi !', 'Je creuse des terriers dans le sable. J\'y trouve des pailles. Arrêtez ça !', 'Je mue ma carapace une fois par an. Tu ne peux pas muer, alors réutilise.', 'Les flaques de marée sont mon salon. Essuie tes pieds — et tes déchets.'] },
  otter: { name: 'Ollie la Loutre', tagline: 'Joueur nettoyeur de rivières.', phrases: ['J\'utilise une pierre comme outil préféré. Même pierre, 20 ans. Champion de la réutilisation !', 'J\'ai une poche sous le bras pour ma pierre. Où est ta poche pour réutiliser ?', 'Je flotte sur le dos et casse des coquillages. Je casse aussi des idées de recyclage.', 'Je me tiens la main avec mes amis en dormant pour ne pas dériver. Tiens la planète aussi.', 'Ma fourrure est la plus dense du règne animal. Gardez le pétrole loin, s\'il vous plaît.'] },
  fish: { name: 'Finn le Poisson', tagline: 'Petit mais puissant pour l\'océan.', phrases: ['Je nage en banc avec 10 000 amis. Ensemble nous sommes une marée de changement.', 'Je respire par mes branchies. Le plastique les obstrue. Gardez l\'eau propre.', 'Je suis petit, mais je mange des algues qui étoufferaient le récif. Petit boulot, grand truc.', 'Mes écailles reflètent la lumière comme un arc-en-ciel. Le plastique non. Ramasse-le !', 'Je suis né en sachant où aller. Assurons-nous que le récif est encore là.'] },
};

const de: PetLocale = {
  octopus: { name: 'Otto der Oktopus', tagline: 'Dein Eco-Maskottchen — kostenloses Starttier.', phrases: ['Acht Arme, acht Upcycling-Projekte gleichzeitig!', 'Ich habe mich durch einen Deckel gequetscht, nur um ihn zu recyceln!', 'Wusstest du, ich habe drei Herzen? Alle grün!', 'Blaues Blut, grüner Lebensstil — das bin ich.', 'Ich öffne Gläser, Flaschen und Köpfe für Recycling.'] },
  turtle: { name: 'Tina die Schildkröte', tagline: 'Langsam und stetig gewinnt das Eco-Rennen.', phrases: ['Ich habe 100 Jahre gelebt — ich habe die Plastikflut steigen sehen.', 'Mein Panzer ist mein Zuhause; der Ozean ist deiner, halt ihn sauber.', 'Ich esse Quallen, keine Plastiktüten. Bitte unterscheide sie!', 'Langsame Schritte überqueren trotzdem den Ozean, Freund.', 'Ich erinnere mich, als dieses Riff keinen Müll hatte. Bringen wir das zurück.'] },
  dolphin: { name: 'Dex der Delfin', tagline: 'Schlau und verspielt in den Wellen.', phrases: ['Ich erkenne mich im Spiegel — und sehe Müll. Lass uns das ändern!', 'Wir nennen einander mit Pfiffen. Ich nenne dich Freund des Meeres.', 'Ich kann einen Flaschendeckel mit der Nase abflippen. Upcycling-Trick!', 'Die Hälfte meines Gehirns schläft, während die andere auf Müll achtet.', 'Ich trage Schwämme auf der Nase als Mode. Wiederverwenden, wiederverwenden!'] },
  whale: { name: 'Willa der Wal', tagline: 'Sanfter Riese der Tiefe.', phrases: ['Mein Gesang reist 16.000 km. Heute singe ich: recyceln.', 'Ich esse Plankton, kein Plastik. Bitte trenne sie.', 'Mein Herz ist so groß wie ein kleines Auto — und es schlägt für den Ozean.', 'Ich atme einmal pro Stunde. Jeder Atem ist kostbar, wie jeder Rest.', 'Das tiefe Blau ist meine Kathedrale. Halt es rein.'] },
  albatross: { name: 'Alby der Albatros', tagline: 'Segelt über der Plastikflut.', phrases: ['Ich fliege 1.000 km pro Tag und sehe jede Plastikflasche unten.', 'Ich blockiere meine Flügel und gleite stundenlang — null Treibstoff, null Müll. Sei wie ich!', 'Ich schöpfe Tintenfische von der Oberfläche. Keine Flaschendeckel. Bitte.', 'Meine Flügel spannen 3,5 m. Groß genug für große Ideen.', 'Ich niste auf abgelegenen Inseln. Nicht einmal sie sind sicher vor Plastik.'] },
  seal: { name: 'Sage der Seehund', tagline: 'Sleeker Wächter der Küste.', phrases: ['Ich tauche 300 m tief. Ich bringe Geschichten, keinen Müll.', 'Meine Schnurrhaare spüren Fische im Dunkeln. Sie spüren auch Mikroplastik. Bäh.', 'Ich sonne mich auf Felsen — und auf Flaschendeckeln. Weniger davon, bitte.', 'Ich halte den Atem zwei Stunden. Lang genug, um einen ganzen Strand zu reinigen.', 'Ich belle meine Jungen an. Heute belle ich Müllsünder an!'] },
  crab: { name: 'Coco die Krabbe', tagline: 'Kleiner recycelnder Schnapper.', phrases: ['Ich laufe seitwärts — in Richtung Nachhaltigkeit, offensichtlich.', 'Meine Klauen schneiden einen Plastikring durch. Rette eine Schildkröte, schneide auch deine!', 'Ich grabe Höhlen im Sand. Ich finde immer Strohhalme darin. Hört auf!', 'Ich häute meinen Panzer einmal pro Jahr. Du kannst dich nicht häuten, also wiederverwende.', 'Gezeitentümpel sind mein Wohnzimmer. Wisch deine Füße — und deinen Müll.'] },
  otter: { name: 'Ollie der Otter', tagline: 'Verspielter Flussreiniger.', phrases: ['Ich nutze einen Stein als Lieblingswerkzeug. Derselbe Stein, 20 Jahre. Wiederverwendungschampion!', 'Ich habe eine Tasche unter dem Arm für meinen Stein. Wo ist deine Tasche für Wiederverwendung?', 'Ich schwimme auf dem Rücken und knacke Muscheln. Ich knacke auch Upcycling-Ideen.', 'Ich halte Hände mit meinen Freunden im Schlaf, damit wir nicht abtreiben. Halt auch den Planeten.', 'Mein Fell ist das dichteste im Tierreich. Halt Öl fern, bitte.'] },
  fish: { name: 'Finn der Fisch', tagline: 'Klein, aber mächtig für den Ozean.', phrases: ['Ich schwimme in einem Schwarm mit 10.000 Freunden. Zusammen sind wir eine Welle des Wandels.', 'Ich atme durch Kiemen. Plastik verstopft sie. Halt das Wasser sauber.', 'Ich bin klein, aber ich esse Algen, die das Riff ersticken würden. Kleiner Job, große Sache.', 'Meine Schuppen reflektieren Licht wie ein Regenbogen. Plastik nicht. Heb es auf!', 'Ich wurde geboren, wohin zu gehen. Sichern wir, dass das Riff noch da ist.'] },
};

const it: PetLocale = {
  octopus: { name: 'Otto il Polpo', tagline: 'La tua mascotte eco — animale iniziale gratuito.', phrases: ['Otto braccia, otto progetti di riciclaggio in una volta!', 'Ho strizzato un tappo solo per riciclarlo!', 'Lo sapevi? Ho tre cuori! Tutti verdi!', 'Sangue blu, stile di vita verde — sono io.', 'Apro barattoli, bottiglie e menti al riciclaggio.'] },
  turtle: { name: 'Tina la Tartaruga', tagline: 'Lento e costante vince la gara eco.', phrases: ['Ho vissuto 100 anni — ho visto la marea di plastica salire.', 'Il mio guscio è la mia casa; l\'oceano è tuo, tienilo pulito.', 'Mangio meduse, non buste di plastica. Impara a distinguerle!', 'Passi lenti attraversano comunque l\'oceano, amico.', 'Ricordo quando questa barriera non aveva rifiuti. Riportiamolo.'] },
  dolphin: { name: 'Dex il Delfino', tagline: 'Intelligente e giocoso tra le onde.', phrases: ['Mi riconosco allo specchio — e vedo rifiuti. Risolviamolo!', 'Ci nomini con fischi. Io ti chiamo Amico del Mare.', 'Posso far saltare un tappo con il muso. Trucco di riciclaggio!', 'Metà del mio cervello dorme mentre l\'altra vigila sui rifiuti.', 'Passo spugne sul muso come moda. Riusare, riusare!'] },
  whale: { name: 'Willa la Balena', tagline: 'Gigante gentile degli abissi.', phrases: ['Il mio canto viaggia per 16.000 km. Oggi canto: ricicla.', 'Mangio plancton, non plastica. Tienili separati.', 'Il mio cuore è grande come una piccola auto — e batte per l\'oceano.', 'Respiro una volta all\'ora. Ogni respiro è prezioso, come ogni scarto.', 'Il blu profondo è la mia cattedrale. Tienila pura.'] },
  albatross: { name: 'Alby l\'Albatros', tagline: 'Vola sopra la marea di plastica.', phrases: ['Volo 1.000 km al giorno e vedo ogni bottiglia di plastica sotto.', 'Blocco le ali e plano per ore — zero carburante, zero rifiuti. Sii come me!', 'Pesco calamari in superficie. Non tappi. Per favore.', 'Le mie ali misurano 3,5 m. Abbastanza per grandi idee.', 'Nido su isole remote. Anche loro non sono salve dalla plastica.'] },
  seal: { name: 'Sage la Foca', tagline: 'Elegante guardiana della riva.', phrases: ['Immersioni a 300 m. Porto storie, non rifiuti.', 'I miei baffi sentono pesci al buio. Sentono anche microplastiche. Bleah.', 'Mi sdraio al sole sulle rocce — e sui tappi. Meno, per favore.', 'Trattengo il respiro due ore. Abbastanza per pulire una spiaggia.', 'Abbaio ai cuccioli. Oggi abbaio a chi sporca!'] },
  crab: { name: 'Coco il Granchio', tagline: 'Piccolo riciclatore schioccante.', phrases: ['Cammino di lato — verso la sostenibilità, ovviamente.', 'Le mie chele tagliano un anello di plastica a metà. Salva una tartaruga, taglia i tuoi!', 'Scavo tane nella sabbia. Continuo a trovare cannucce. Smettetela!', 'Muto il guscio una volta all\'anno. Tu non puoi, quindi riusa.', 'Le pozze di marea sono il mio salotto. Pulisci i piedi — e i rifiuti.'] },
  otter: { name: 'Ollie la Lontra', tagline: 'Giocoso pulitore di fiumi.', phrases: ['Uso un sasso come strumento preferito. Stesso sasso, 20 anni. Campione del riuso!', 'Ho una tasca sotto il braccio per il sasso. Dov\'è la tua tasca per il riuso?', 'Galleggio sulla schiena e apro conchiglie. Apro anche idee di riciclaggio.', 'Mi tengo per mano con gli amici dormendo per non derivare. Tieni anche il pianeta.', 'Il mio pelo è il più denso del regno animale. Tenete l\'olio lontano, per favore.'] },
  fish: { name: 'Finn il Pesce', tagline: 'Piccolo ma potente per l\'oceano.', phrases: ['Nuoto in banco con 10.000 amici. Insieme siamo una marea di cambiamento.', 'Respiro con le branchie. La plastica le ostruisce. Tieni l\'acqua pulita.', 'Sono piccolo, ma mangio alghe che soffocherebbero la barriera. Lavoro piccolo, grande cosa.', 'Le mie squame riflettono luce come un arcobaleno. La plastica no. Raccoglila!', 'Sono nato sapendo dove andare. Assicuriamoci che la barriera ci sia ancora.'] },
};

const ja: PetLocale = {
  octopus: { name: 'タコのオットー', tagline: 'あなたのエコマスコット — 無料の最初のペット。', phrases: ['8本の腕で、8つのアップサイクルプロジェクトを同時に！', 'リサイクルするために瓶の蓋をくぐり抜けたよ！', '知ってた？心臓が3つあるんだ。全部グリーン！', '青い血、グリーンな暮らし — それが僕。', '瓶もボトルもリサイクルの心も開けるよ。'] },
  turtle: { name: 'ウミガメのティナ', tagline: 'ゆっくり着実にエコレースを勝つ。', phrases: ['100年生きてきた — プラスチックの波が上がるのを見た。', '私の甲羅は私の家；海はあなたのもの、きれいにしてね。', '私はクラゲを食べる、レジ袋じゃない。見分けてね！', 'ゆっくりした歩みでも海を渡れる、友よ。', 'この礁にゴミがなかった頃を覚えてる。取り戻そう。'] },
  dolphin: { name: 'イルカのデックス', tagline: '波の中で賢く遊ぶ。', phrases: ['鏡で自分を認識する — ゴミも見える。直そう！', '私たちは口笛で名付け合う。あなたを「海の友」と呼ぶよ。', '鼻で瓶の蓋を飛ばせる。リサイクルトリック！', '脳の半分は眠り、半分はゴミを見張る。', '鼻にスポンジを付けておしゃれ。再利用、再利用！'] },
  whale: { name: 'クジラのウィラ', tagline: '深淵の優しい巨人。', phrases: ['私の歌は16,000km届く。今日は歌う：リサイクルしよう。', 'プランクトンを食べる、プラスチックじゃない。分けてね。', '私の心臓は車ほど — 海のために鼓動する。', '1時間に1回呼吸する。すべての呼吸は、すべての端切れのように貴重。', '深い青は私の聖堂。きれいに保って。'] },
  albatross: { name: 'アホウドリのアルビー', tagline: 'プラスチックの波の上を滑空。', phrases: ['1日1,000km飛び、下のプラスチックボトルをすべて見る。', '翼を固定して何時間も滑空 — ゼロ燃料、ゼロゴミ。私のように！', '表面からイカをすくう。瓶の蓋じゃない。お願い。', '翼は3.5m。大きなアイデアを運べる。', '離れ小島に巣を作る。そこもプラスチックから安全じゃない。'] },
  seal: { name: 'アザラシのセージ', tagline: '岸辺のスマートな守護者。', phrases: ['300m潜れる。持ち帰るのは物語、ゴミじゃない。', 'ヒゲは暗闇で魚を感じる。マイクロプラスチックも感じる。うえぇ。', '岩に日向ぼっこ — 蓋の上にも。もっと少なく、お願い。', '2時間息を止められる。海岸全体を掃除できる。', '子供に吠える。今日はポイ捨てする人に吠える！'] },
  crab: { name: 'カニのココ', tagline: 'パチパチ小さなリサイクラー。', phrases: ['横歩き — サステナビリティに向かって、当然。', 'ハサミでプラスチックリングを切れる。亀を救おう、あなたのも切って！', '砂に穴を掘る。ストローばかり見つかる。やめて！', '年1回脱皮する。あなたは脱皮できない、だから再利用して。', '潮だまりは私の居間。足もゴミも拭いて。'] },
  otter: { name: 'カワウソのオリ―', tagline: '川の遊び好きな掃除屋。', phrases: ['お気に入りの道具は石。同じ石20年。再利用の王者！', '腕の下に石用のポケット。あなたの再利用ポケットは？', '仰向けに浮かんで貝を割る。リサイクルアイデアも割る。', '寝ながら友と手をつなぐ。流されないように。地球もつなごう。', '私の毛は動物界で一番密集。油を入れないで、お願い。'] },
  fish: { name: '魚のフィン', tagline: '海のために小さくても強い。', phrases: ['1万の友と群れで泳ぐ。一緒に変化の波。', 'えらで呼吸。プラスチックは詰まらせる。水をきれいに。', '小さいけど、礁を窒息させる藻を食べる。小さな仕事、大きなこと。', '鱗は虹のように光る。プラスチックは違う。拾って！', 'どこへ行くか生まれながらに知ってる。礁がまだあるか確かめよう。'] },
};

const zh: PetLocale = {
  octopus: { name: '章鱼奥托', tagline: '你的环保吉祥物 — 免费初始宠物。', phrases: ['八只手臂，八个升级改造项目同时进行！', '我挤过罐盖就为了回收它！', '知道吗？我有三颗心！都是绿色的！', '蓝血，绿色生活 — 这就是我。', '我能打开罐子、瓶子和回收的心。'] },
  turtle: { name: '海龟蒂娜', tagline: '慢而稳赢得环保赛跑。', phrases: ['我活了一百年 — 我看到塑料潮上涨。', '我的壳是我的家；海洋是你的，保持清洁。', '我吃水母，不吃塑料袋。请分辨清楚！', '慢步也能穿越海洋，朋友。', '我记得这片礁石没有垃圾的时候。让我们恢复那样。'] },
  dolphin: { name: '海豚德克斯', tagline: '聪明活泼在浪中。', phrases: ['我在镜中认出自己 — 也看到垃圾。让我们解决它！', '我们用哨声互相命名。我叫你海洋之友。', '我可以用鼻子弹开瓶盖。回收技巧！', '我半个大脑睡觉时另一半监视垃圾。', '我鼻上挂海绵当时尚。再利用，再利用！'] },
  whale: { name: '鲸鱼威拉', tagline: '深渊的温柔巨人。', phrases: ['我的歌声传16,000公里。今天我唱：回收。', '我吃浮游生物，不吃塑料。请分开它们。', '我的心像小车一样大 — 为海洋跳动。', '我每小时呼吸一次。每次呼吸都珍贵，像每片废料。', '深蓝是我的教堂。保持纯净。'] },
  albatross: { name: '信天翁阿尔比', tagline: '在塑料潮上滑翔。', phrases: ['我一天飞1,000公里，看到下面每个塑料瓶。', '我锁住翅膀滑翔数小时 — 零燃料，零垃圾。像我一样！', '我从水面捞鱿鱼。不是瓶盖。拜托。', '我的翅膀3.5米。足以承载大想法。', '我在偏远岛屿筑巢。连它们也不能免于塑料。'] },
  seal: { name: '海豹塞吉', tagline: '海岸的优雅守护者。', phrases: ['我能潜300米深。带回故事，不是垃圾。', '我的胡须在黑暗中感受鱼。也感受微塑料。恶心。', '我在岩石上晒太阳 — 也在瓶盖上。请少一点。', '我憋气两小时。够清理整个海滩。', '我对幼崽吠叫。今天我对乱扔者吠叫！'] },
  crab: { name: '螃蟹可可', tagline: '咔嚓的小回收者。', phrases: ['我横着走 — 朝可持续走，当然。', '我的钳子能剪断塑料环。救只海龟，也剪你的！', '我在沙里挖洞。总找到吸管。别这样！', '我每年蜕壳一次。你不能蜕，所以再利用。', '潮池是我的客厅。擦你的脚 — 和你的垃圾。'] },
  otter: { name: '水獭奥利', tagline: '活泼的河流清洁者。', phrases: ['我用石头做工具。同一块石头20年。再利用冠军！', '我臂下有口袋装石头。你的再利用口袋呢？', '我仰浮着敲开贝壳。也敲开回收想法。', '我睡觉时和朋友牵手以免漂走。也握住地球。', '我的毛是动物界最密的。请远离石油。'] },
  fish: { name: '鱼芬恩', tagline: '小而强为海洋。', phrases: ['我和一万朋友成群。一起我们是变化之潮。', '我用鳃呼吸。塑料堵塞它们。保持水清洁。', '我小，但我吃会窒息礁石的藻。小工作，大意义。', '我的鳞片像彩虹反射光。塑料不会。捡起它！', '我天生知道去哪。让我们确保礁石还在。'] },
};

const ko: PetLocale = {
  octopus: { name: '문어 오토', tagline: '당신의 에코 마스코트 — 무료 시작 펫.', phrases: ['팔이 여덟 개, 업사이클링 프로젝트도 여덟 개 동시에!', '재활용하려고 뚜껑을 통과했어요!', '아시나요? 심장이 세 개! 모두 초록!', '푸른 피, 초록 생활 — 그게 저예요.', '병도 마음도 재활용으로 열어요.'] },
  turtle: { name: '거북 티나', tagline: '느리고 꾸준히 에코 경주에서 이겨요.', phrases: ['100년 살았어요 — 플라스틱 물결이 오르는 걸 봤어요.', '제 집은 껍질; 바다는 당신 것, 깨끗이 해주세요.', '저는 해파리를 먹지, 비닐봉지가 아니에요. 구분해주세요!', '느린 걸음도 바다를 건너요, 친구.', '이 암초에 쓰레기 없던 때 기억해요. 되돌려요.'] },
  dolphin: { name: '돌고래 덱스', tagline: '파도 속 총명하고 장난꾸러기.', phrases: ['거울에서 저를 알아봐요 — 쓰레기도 보여요. 고쳐요!', '우리는 휘파람으로 이름 지어요. 당신을 바다의 친구라 불러요.', '코로 뚜껑을 날려요. 재활용 트릭!', '뇌 반쪽은 자고 반쪽은 쓰레기를 지켜봐요.', '코에 해면을 패션으로 끼요. 재사용, 재사용!'] },
  whale: { name: '고래 윌라', tagline: '심연의 온화한 거인.', phrases: ['제 노래는 16,000km 가요. 오늘은: 재활용.', '플랑크톤을 먹지, 플라스틱이 아니에요. 분리해주세요.', '제 심장은 작은 차만 해요 — 바다를 위해 뛰어요.', '한 시간에 한 번 숨 쉬어요. 모든 숨은 귀중해요.', '깊은 푸른은 제 성당. 깨끗이 해주세요.'] },
  albatross: { name: '알바트로스 알비', tagline: '플라스틱 물결 위로 활공.', phrases: ['하루 1,000km 날아 아래 모든 플라스틱 병을 봐요.', '날개를 고정하고 시간 동안 활공 — 연료 영, 쓰레기 영. 저처럼!', '표면에서 오징어를 떠요. 뚜껑이 아니에요. 제발.', '제 날개는 3.5m. 큰 아이디어를 실어요.', '외딴 섬에 둥지를 틀어요. 거기도 플라스틱에서 안전하지 않아요.'] },
  seal: { name: '물개 세이지', tagline: '해안의 날렵한 수호자.', phrases: ['300m 잠수해요. 이야기를 가져와요, 쓰레기가 아니에요.', '제 수염은 어둠에서 물고기를 느껴요. 미세플라스틱도. 으.', '바위에 햇볕을 — 뚜껑 위에도. 더 적게, 제발.', '숨을 2시간 참아요. 해변 전체를 청소할 만큼.', '새끼에게 짖어요. 오늘은 쓰레기꾼에게 짖어요!'] },
  crab: { name: '게 코코', tagline: '딱딱 작은 재활용가.', phrases: ['옆으로 걸어요 — 지속가능성으로, 당연히.', '제 집으로 플라스틱 링을 잘라요. 거북을 구해요, 당신도 잘라요!', '모래에 굴을 파요. 빨대를 자꾸 찾아요. 그만!', '일 년에 한 번 껍질을 벗어요. 당신은 못 벗으니 재사용해요.', '조수웅덩이는 제 거실. 발도 쓰레기도 닦아요.'] },
  otter: { name: '수달 올리', tagline: '장난스러운 강 청소부.', phrases: ['돌을 도구로 써요. 같은 돌 20년. 재사용 챔피언!', '팔 아래 돌 주머니가 있어요. 당신의 재사용 주머니는?', '등에 떠서 조개를 깨요. 재활용 아이디어도 깨요.', '자면서 친구와 손잡아요. 떠내려가지 않게. 지구도 잡아요.', '제 털은 동물계에서 가장 빽빽해요. 기름 멀리 해주세요.'] },
  fish: { name: '물고기 핀', tagline: '바다를 위해 작지만 강해요.', phrases: ['만 명의 친구와 무리지어요. 함께 변화의 물결.', '아가미로 숨 쉬어요. 플라스틱이 막아요. 물 깨끗이.', '작지만 암초를 질식시킬 조류를 먹어요. 작은 일, 큰 일.', '비늘은 무지개처럼 빛나요. 플라스틱은 아니에요. 주워요!', '태어날 때 어디 갈지 알아요. 암초가 여전히 있는지 확인해요.'] },
};

const ru: PetLocale = {
  octopus: { name: 'Осьминог Отто', tagline: 'Ваш эко-талисман — бесплатный начальный питомец.', phrases: ['Восемь рук — восемь апсайкл-проектов сразу!', 'Я протиснулся через крышку, чтобы её переработать!', 'Знал ли ты? У меня три сердца! Все зелёные!', 'Голубая кровь, зелёный образ жизни — это я.', 'Я открываю банки, бутылки и умы для переработки.'] },
  turtle: { name: 'Черепаха Тина', tagline: 'Медленно и верно побеждает в эко-гонке.', phrases: ['Я живу 100 лет — видела, как поднимается пластик.', 'Мой панцирь — мой дом; океан — твой, держи его чистым.', 'Я ем медуз, не полиэтиленовые пакеты. Учитесь различать!', 'Медленные шаги тоже пересекают океан, друг.', 'Помню, когда этот риф не знал мусора. Вернём это.'] },
  dolphin: { name: 'Дельфин Декс', tagline: 'Умный и игривый в волнах.', phrases: ['Я узнаю себя в зеркале — и вижу мусор. Исправим это!', 'Мы называем друг друга свистом. Я зову тебя Друг Моря.', 'Я могу подбросить крышку носом. Трюк переработки!', 'Половина мозга спит, другая стережёт мусор.', 'Я ношу губки на носу как мода. Повторное использование!'] },
  whale: { name: 'Кит Уилла', tagline: 'Мягкий гигант глубин.', phrases: ['Моя песня летит на 16 000 км. Сегодня я пою: перерабатывай.', 'Я ем планктон, не пластик. Разделяй их.', 'Моё сердце размером с маленькую машину — и бьётся за океан.', 'Я дышу раз в час. Каждый вдох драгоценен, как каждый остаток.', 'Глубокая синева — мой собор. Храни её чистой.'] },
  albatross: { name: 'Альбатрос Элби', tagline: 'Парит над пластиковой волной.', phrases: ['Я лечу 1 000 км в день и вижу каждую бутылку внизу.', 'Я фиксирую крылья и парю часами — ноль топлива, ноль мусора. Будь как я!', 'Я черпаю кальмаров с поверхности. Не крышки. Пожалуйста.', 'Мои крылья — 3,5 м. Достаточно для больших идей.', 'Я гнездюсь на отдалённых островах. Даже там нет защиты от пластика.'] },
  seal: { name: 'Тюлень Сейдж', tagline: 'Элегантный страж берега.', phrases: ['Я ныряю на 300 м. Приношу истории, не мусор.', 'Мои усы чувствуют рыбу в темноте. И микропластик. Фу.', 'Я греюсь на скалах — и на крышках. Меньше, пожалуйста.', 'Я держу дыхание два часа. Достаточно, чтобы убрать пляж.', 'Я лаю на детёнышей. Сегодня лаю на мусорщиков!'] },
  crab: { name: 'Краб Коко', tagline: 'Шустрый маленький переработчик.', phrases: ['Я хожу боком — к устойчивости, очевидно.', 'Мои клешни режут пластиковое кольцо. Спаси черепаху, режь свои тоже!', 'Я копаю норки в песке. Всё время нахожу трубочки. Хватит!', 'Я линяю раз в год. Ты не можешь, поэтому переиспользуй.', 'Приливные лужи — моя гостиная. Вытирай ноги — и мусор.'] },
  otter: { name: 'Выдра Олли', tagline: 'Игривый чистильщик рек.', phrases: ['Я использую камень как инструмент. Тот же камень 20 лет. Чемпион!', 'У меня карман под лапой для камня. Где твой для переиспользования?', 'Я плаваю на спине и колю ракушки. Колю и идеи апсайкла.', 'Я держу друзей за руки во сне. Держи и планету тоже.', 'Мой мех — самый плотный в царстве животных. Нефть — прочь.'] },
  fish: { name: 'Рыба Финн', tagline: 'Маленький, но сильный для океана.', phrases: ['Я плаваю стаей с 10 000 друзей. Вместе — волна перемен.', 'Я дышу жабрами. Пластик забивает их. Держи воду чистой.', 'Я мал, но ем водоросли, что задушат риф. Малое дело — большое.', 'Моя чешуя блестит радугой. Пластик — нет. Подними его!', 'Я родился зная куда. Убедимся, что риф ещё там.'] },
};

const ar: PetLocale = {
  octopus: { name: 'أوتو الأخطبوط', tagline: 'تعويذتك البيئية — حيوان البداية المجاني.', phrases: ['ثمانية أذرع، ثمانية مشاريع إعادة تدوير دفعة واحدة!', 'عصرت عبر غطاء جرة فقط لأعيد تدويره!', 'هل تعلم أن لي ثلاثة قلوب؟ كلها خضراء!', 'دم أزرق، حياة خضراء — هذا أنا.', 'أفتح الجرار والزجاج والعقول للتدوير.'] },
  turtle: { name: 'تينا السلحفاة', tagline: 'بطيء وثابت يفوز في سباق البيئة.', phrases: ['عشت 100 سنة — رأيت مد البلاستيك يرتفع.', 'صدفتي بيتي؛ المحيط لك، حافظ عليه نظيفاً.', 'آكل قنديل البحر لا الأكياس البلاستيكية. ميز بينها!', 'خطوات بطيئة تعبر المحيط أيضاً يا صديقي.', 'أتذكر حين كان هذا الشعاب المرجانية بلا قمامة. لنعد إليه.'] },
  dolphin: { name: 'ديكس الدولفين', tagline: 'ذكي ومرح في الأمواج.', phrases: ['أتعرّف على نفسي في المرآة — وأرى القمامة. لنصلحها!', 'نسمي بعضنا بالصفير. أدعوك صديق البحر.', 'أستطيع قلب غطاء بزعنف. حيلة إعادة تدوير!', 'نصف دماغي ينام بينما الآخر يراقب القمامة.', 'أضع إسفنج على زعنفي كموضة. أعِد الاستخدام!'] },
  whale: { name: 'ويلا الحوت', tagline: 'عملاق لطيف في الأعماق.', phrases: ['نشيد يصل 16,000 كم. اليوم أغني: أعِد التدوير.', 'آكل العوالق لا البلاستيك. افصل بينهما.', 'قلبي بحجم سيارة صغيرة — ينبض للمحيط.', 'أتنفس مرة كل ساعة. كل نَفَس ثمين ككل بقايا.', 'الأزرق العميق كاتدرائيتي. حافظ عليه نقياً.'] },
  albatross: { name: 'ألبي القطرس', tagline: 'يحلّق فوق مد البلاستيك.', phrases: ['أطير 1,000 كم يومياً وأرى كل زجاجة بلاستيك بالأسفل.', 'أثبّت جناحي وأنزلق ساعات — وقود صفر، قمامة صفر. كن مثلي!', 'ألتقط الحبار من السطح. لا الأغطية. من فضلك.', 'باع جناحي 3.5م. يكفي لحمل أفكار كبيرة.', 'أعشّش في جزر نائية. حتى هي ليست آمنة من البلاستيك.'] },
  seal: { name: 'ساجي الفقمة', tagline: 'حارس أنيق للشاطئ.', phrases: ['أغوص 300م. أعيد بقصص لا قمامة.', 'شارباتي تحس بالسمك في الظلام. وبالميكروبلاستيك. مقزز.', 'أستحم في الشمس على الصخور — وعلى الأغطية. أقل من ذلك.', 'أحبس نفسي ساعتين. يكفي لتنظيف شاطئ.', 'أنبح على صغاري. اليوم أنبح على من يلقون القمامة!'] },
  crab: { name: 'كوكو السلطعون', tagline: 'مُعيد تدوير صغير مفصص.', phrases: ['أمشي جانبياً — نحو الاستدامة، بالطبع.', 'مخالبي تقطع حلقة بلاستيك. أنقذ سلحفاة، اقطع حلقاتك!', 'أحفر جحوراً في الرمل. أجد مصاصات فيها. توقفوا!', 'أطرح صدفتي مرة سنوياً. أنت لا تستطيع، فأعِد الاستخدام.', 'برك المد والجزر صالوني. امسح قدميك — وقمامتك.'] },
  otter: { name: 'أولي القضاعة', tagline: 'منظف أنهار مرح.', phrases: ['أستخدم صخرة كأداتي المفضلة. نفس الصخرة 20 سنة. بطل!', 'لي جيب تحت ذراعي لصخرتي. أين جيبك لإعادة الاستخدام؟', 'أطفو على ظهري وأكسر المحار. أكسر أفكار إعادة التدوير.', 'أمسك أيدي أصدقائي أثناء النوم. أمسك الكوكب أيضاً.', 'فري هو الأكثف في المملكة الحيوانية. أبعد النفط عنه.'] },
  fish: { name: 'فين السمكة', tagline: 'صغيرة لكن قوية للمحيط.', phrases: ['أسبح في سرب مع 10,000 صديق. معاً مد التغيير.', 'أتنفس بالخياشيم. البلاستيك يسدها. حافظ على المياه.', 'أنا صغير، لكن آكل طحالب تخنق الشعاب. عمل صغير، أمر كبير.', 'حرشفي تعكس الضوء كقوس قزح. البلاستيك لا. التقطه!', 'ولدت أعرف أين أذهب. لنتأكد أن الشعاب لا تزال هناك.'] },
};

const hi: PetLocale = {
  octopus: { name: 'ऑटो ऑक्टोपस', tagline: 'आपका इको शुभंकर — मुफ्त शुरुआती पालतू।', phrases: ['आठ भुजाएँ, एक साथ आठ अपसाइकिल प्रोजेक्ट!', 'मैं ढक्कन से निकला बस उसे रीसाइकल करने के लिए!', 'पता है? मेरे तीन दिल हैं! सब हरे!', 'नीला खून, हरा जीवन — वही मैं।', 'मैं जार, बोतलें और दिमाग खोलता हूँ रीसाइकिलिंग के लिए।'] },
  turtle: { name: 'टीना कछुआ', tagline: 'धीरे और निरंतर इको दौड़ जीतता है।', phrases: ['मैंने 100 साल जिए — प्लास्टिक की लहर बढ़ती देखी।', 'मेरा खोल मेरा घर; समुद्र आपका, साफ रखिए।', 'मैं जेलीफिश खाता हूँ, प्लास्टिक की थैलियाँ नहीं। अंतर पहचानिए!', 'धीमे कदम भी समुद्र पार करते हैं, दोस्त।', 'मुझे याद है जब यह चट्टान कचरे से साफ थी। वैसा करें।'] },
  dolphin: { name: 'डेक्स डॉलफिन', tagline: 'लहरों में समझदार और चंचल।', phrases: ['मैं आईने में खुद को पहचानता हूँ — कचरा भी देखता हूँ। ठीक करें!', 'हम सीटी से नाम रखते हैं। मैं तुम्हें समुद्र मित्र कहता हूँ।', 'मैं नाक से ढक्कन उछाल सकता हूँ। रीसाइकिल ट्रिक!', 'आधा दिमाग सोता है आधा कचरा देखता।', 'मैं नाक पर स्पंज पहनता हूँ। पुनर्प्रयोग!'] },
  whale: { name: 'विल्ला व्हेल', tagline: 'गहराई की कोमल दिग्गज।', phrases: ['मेरा गाना 16,000 किमी जाता। आज गाती: रीसाइकल।', 'मैं प्लावक खाती, प्लास्टिक नहीं। अलग रखिए।', 'मेरा दिल छोटी कार जितना — समुद्र के लिए धड़कता।', 'मैं घंटे में एक बार साँस लेती। हर साँस कीमती, हर बचत।', 'गहरा नीला मेरा मंदिर। शुद्ध रखिए।'] },
  albatross: { name: 'एल्बी एल्बाट्रॉस', tagline: 'प्लास्टिक लहर के ऊपर उड़ता।', phrases: ['मैं एक दिन 1,000 किमी उड़ता और नीचे हर बोतल देखता।', 'पंख बाँध घंटों सरकता — जीरो ईधन, जीरो कचरा। मेरे जैसे बनो!', 'सतह से स्क्विड निकालता। ढक्कन नहीं। कृपया।', 'पंख 3.5 मीटर। बड़े विचार ले जाने को।', 'दूर द्वीपों पर घोंसला। वे भी प्लास्टिक से सुरक्षित नहीं।'] },
  seal: { name: 'सेज सील', tagline: 'तट की सुरुचिपूर्ण रक्षक।', phrases: ['300 मीटर गोता। कहानियाँ लाती, कचरा नहीं।', 'मेरी मूँछें अँधेरे में मछली से जानती — माइक्रोप्लास्टिक भी। ब्यह।', 'चट्टान पर धूप — ढक्कन पर भी। कम करें।', 'दो घंटे साँस रोकती। समुद्र तट साफ करने को।', 'शावकों को भौंकती। आज कचरेबाजों को!'] },
  crab: { name: 'कोको केकड़ा', tagline: 'तड़क भड़क छोटा रीसाइक्लर।', phrases: ['मैं तिरछा चलता — सस्टेनेबिलिटी की ओर, स्पष्ट।', 'मेरे पंजे प्लास्टिक रिंग काटते। कछुआ बचाओ, अपना काटो!', 'रेत में बिल खोदता। परती पाता। बंद करो!', 'साल में एक बार केवल बदलता। तुम नहीं, पुनर्प्रयोग करो।', 'ज्वार पोखर मेरा ड्राइंग रूम। पैर और कचरा पोंछो।'] },
  otter: { name: 'ओली ओटर', tagline: 'नदी का चंचल सफाई कर्मी।', phrases: ['पसंदीदा औज़ार पत्थर। वही पत्थर 20 साल। पुनर्प्रयोग चैंपियन!', 'बाजू के नीचे जेब पत्थर की। तुम्हारी पुनर्प्रयोग जेब?', 'पीठ पर तैर के शंख तोड़ता। रीसाइकिल विचार भी।', 'सोते में दोस्तों से हाथ। ग्रह भी थामो।', 'मेरे बाल जानवर जगत में सबसे घने। तेल दूर रखो।'] },
  fish: { name: 'फिन मछली', tagline: 'समुद्र के लिए छोटी पर शक्तिशाली।', phrases: ['10,000 दोस्तों से झुंड। मिलकर बदलाव की लहर।', 'गलफड़ों से साँस। प्लास्टिक रोकता। पानी साफ रखो।', 'छोटा पर चट्टान घुटने वाली शैवाल खाता। छोटा काम, बड़ी बात।', 'पंख इंद्रधनुष सा चमके। प्लास्टिक नहीं। उठाओ!', 'जन्म से रास्ता जानता। चट्टान अब भी हो, सुनिश्चित करो।'] },
};

export const PET_LOCALES: Record<LangCode, PetLocale> = { en, pt, es, fr, de, it, ja, zh, ko, ru, ar, hi };

export function getLocalizedPet(petKey: string, lang: LangCode): LocalizedPet {
  const locale = PET_LOCALES[lang] ?? en;
  return locale[petKey] ?? en[petKey] ?? en.octopus;
}
